project:
  type: website
  output-dir: docs

website:
  title: "Saida Tirado Caicedo"
  image: s.png
  navbar:
    logo: s.png
    title: false  
    left:
      - href: index.qmd
        text: Hola
      - href: about_me.qmd
        text: Sobre mí
      - href: formacion
        text: Formación Académica
      - href: hobbies
        text: Pasatiempos
      - end.qmd


format:
  html:
    theme: menta
    css: styles.css
    toc: true
    toc-location: right
    toc-title: Contenidos



