---
title: "Mis Pasatiempos"
---

*Si desean conocerme más a profundidad, en esta sección podrán hacerlo.*

### *Arte*

*Me gusta ver a los artistas realizando retratos de la naturaleza, siento que puedo tener un sentimiento de relajación, aunque no soy buena dibujando, es algo que me llama mucho la atención.*

### *Música*

*Me encanta la música, no soy buena cantando, pero sé tocar la flauta y un poco la guitarra. Me gustaria aprender a tocar el piano.*

### *Deportes*

*Cuando era más joven solia jugar básquet, gane un campeonato de fútbol en mi colegio. Aunque ya no realizo ninguno de estos dos deportes, me gusta ejercitarme seguido para mantener mi cuerpo en forma y saludable.*

### *Académicos* 

*Siempre he intentado que mis calificaciones sean altas, he recibido cuadros de honor durante mi tiempo en la primaria y preperatoria. Logre ingresar a una de las mejores universidades de mi pais y actualmente estoy cursando mi carrera en ella. Estoy muy agradecida por todas las personas que me han apoyado durante este proceso.*
